local c = require("sigma.colors")

return {
    CmpItemAbbr              = { fg = c.fg },
    CmpItemAbbrDeprecated    = { fg = c.fg, strikethrough = true },
    CmpItemAbbrMatch         = { fg = c.pinkNeon },
    CmpItemAbbrMatchFuzzy    = { link = "CmpItemAbbrMatchFuzzy" },
    CmpItemMenu              = { fg = c.invisibleGrey },

    CmpItemKindDefault       = { link = "UNSET" },

    CmpItemKindClass         = { link = "Type" },
    CmpItemKindConstant      = { link = "Constant" },
    CmpItemKindConstructor   = { link = "Function" },
    CmpItemKindEnum          = { link = "Type" },
    CmpItemKindEnumMember    = { link = "CmpItemKindEnum" },
    CmpItemKindEvent         = { link = "UNSET" },
    CmpItemKindField         = { link = "@variable.member" },
    CmpItemKindFile          = { fg = c.orangeDimmed },
    CmpItemKindFunction      = { link = "Function" },
    CmpItemKindInterface     = { link = "@lsp.type.interface" },
    CmpItemKindKeyword       = { link = "Keyword" },
    CmpItemKindMethod        = { link = "Function" },
    CmpItemKindModule        = { link = "@module" },
    CmpItemKindOperator      = { link = "Operator" },
    CmpItemKindProperty      = { link = "@property" },
    CmpItemKindReference     = { link = "Identifier" },
    CmpItemKindSnippet       = { fg = c.invisibleGrey },
    CmpItemKindStruct        = { link = "Structure" },
    CmpItemKindText          = { link = "Normal" },
    CmpItemKindTypeParameter = { link = "UNSET" },
    CmpItemKindUnit          = { link = "UNSET" },
    CmpItemKindValue         = { link = "UNSET" },
    CmpItemKindVariable      = { link = "Identifier" },
}
