local c = require("sigma.colors")

return {
    -- BlinkCmpAbbr              = { fg = c.fg },
    -- BlinkCmpAbbrDeprecated    = { fg = c.fg, strikethrough = true },
    -- BlinkCmpAbbrMatch         = { fg = c.pinkNeon },
    -- BlinkCmpAbbrMatchFuzzy    = { link = "CmpItemAbbrMatchFuzzy" },
    -- BlinkCmpMenu              = { fg = c.invisibleGrey },

    BlinkCmpKind = { link = "UNSET" },

    -- BlinkCmpKindClass         = { link = "@lsp.type.type" },
    -- BlinkCmpKindConstant      = { link = "Constant" },
    -- BlinkCmpKindConstructor   = { link = "@lsp.type.function" },
    -- BlinkCmpKindEnum          = { link = "@lsp.type.enum" },
    -- BlinkCmpKindEnumMember    = { link = "@lsp.type.enumMember" },
    -- BlinkCmpKindEvent         = { link = "@lsp.type.type" },
    -- BlinkCmpKindField         = { link = "@variable.member" },
    -- BlinkCmpKindFile          = { fg = c.orangeDimmed },
    -- BlinkCmpKindFunction      = { link = "@lsp.type.function" },
    -- BlinkCmpKindInterface     = { link = "@lsp.type.interface" },
    -- BlinkCmpKindKeyword       = { link = "Keyword" },
    -- BlinkCmpKindMethod        = { link = "@lsp.type.method" },
    -- BlinkCmpKindModule        = { link = "@module" },
    -- BlinkCmpKindOperator      = { link = "Operator" },
    -- BlinkCmpKindProperty      = { link = "@lsp.type.property" },
    -- BlinkCmpKindReference     = { link = "Identifier" },
    -- BlinkCmpKindSnippet       = { fg = c.invisibleGrey },
    -- BlinkCmpKindStruct        = { link = "@lsp.type.struct" },
    -- BlinkCmpKindText          = { link = "Normal" },
    -- BlinkCmpKindTypeParameter = { link = "@lsp.type.typeParameter" },
    -- BlinkCmpKindUnit          = { link = "Number" },
    -- BlinkCmpKindValue         = { link = "Number" },
    -- BlinkCmpKindVariable      = { link = "@lsp.type.variable" },


    BlinkCmpKindClass         = { fg = c.bg, bg = c.blueIce },
    BlinkCmpKindColor         = { fg = c.fg, bg = c.pinkDimmed },
    BlinkCmpKindConstant      = { fg = c.fg, bg = c.darkCyan },
    BlinkCmpKindConstructor   = { fg = c.bg, bg = c.lightCyan },
    BlinkCmpKindEnum          = { fg = c.bg, bg = c.blueIce },
    BlinkCmpKindEnumMember    = { fg = c.fg, bg = c.darkCyan },
    BlinkCmpKindEvent         = { fg = c.bg, bg = c.blueIce },
    BlinkCmpKindField         = { fg = c.bg, bg = c.lightBlue },
    BlinkCmpKindFile          = { fg = c.bg, bg = c.orangeDimmed },
    BlinkCmpKindFolder        = { link = "BlinkCmpKindFile" },
    BlinkCmpKindFunction      = { fg = c.bg, bg = c.lightCyan },
    BlinkCmpKindInterface     = { fg = c.bg, bg = c.blueIce },
    BlinkCmpKindKeyword       = { fg = c.bg, bg = c.pinkNeon },
    BlinkCmpKindMethod        = { fg = c.bg, bg = c.lightCyan },
    BlinkCmpKindModule        = { fg = c.fg, bg = c.darkCyan },
    BlinkCmpKindOperator      = { fg = c.bg, bg = c.bleachedCyan },
    BlinkCmpKindProperty      = { fg = c.bg, bg = c.lightBlue },
    BlinkCmpKindReference     = { fg = c.bg, bg = c.whiteIsh },
    BlinkCmpKindSnippet       = { fg = c.fg, bg = c.invisibleGrey },
    BlinkCmpKindStruct        = { fg = c.fg, bg = c.darkCyan },
    BlinkCmpKindText          = { fg = c.bg, bg = c.fg },
    BlinkCmpKindTypeParameter = { fg = c.bg, bg = c.blueIce },
    BlinkCmpKindUnit          = { fg = c.bg, bg = c.pinkDimmed },
    BlinkCmpKindValue         = { fg = c.bg, bg = c.pinkDimmed },
    BlinkCmpKindVariable      = { fg = c.bg, bg = c.whiteIsh },
}
