local c = require("sigma.colors")

return {
    DapBreakpoint                = { fg = c.error, bg = c.line_bg },
    DapBreakpointCondition       = { fg = c.warning, bg = c.line_bg },
    DapBreakpointRejected        = { fg = c.error, bg = c.line_bg },
    DapLogPoint                  = { fg = c.info, bg = c.line_bg },
    DapStopped                   = { fg = c.hint, bg = c.line_bg },

    DapUINormal                  = { link = "Normal" },
    DapUIVariable                = { link = "@variable" },
    DapUIScope                   = { fg = c.darkCyan },
    DapUIType                    = { link = "@type" },
    DapUIValue                   = { link = "Normal" },
    DapUIModifiedValue           = { fg = c.darkCyan, bold = true },
    DapUIDecoration              = { fg = c.darkCyan },
    DapUIThread                  = { fg = c.cyanGreen },
    DapUIStoppedThread           = { fg = c.darkCyan },
    DapUIFrameName               = { link = "Normal" },
    DapUISource                  = { fg = c.purple },
    DapUILineNumber              = { fg = c.darkCyan },
    DapUIFloatNormal             = { link = "NormalFloat" },
    DapUIFloatBorder             = { fg = c.darkCyan },
    DapUIWatchesEmpty            = { fg = c.pinkNeon },
    DapUIWatchesValue            = { fg = c.cyanGreen },
    DapUIWatchesError            = { fg = c.pinkNeon },
    DapUIBreakpointsPath         = { fg = c.darkCyan },
    DapUIBreakpointsInfo         = { fg = c.cyanGreen },
    DapUIBreakpointsCurrentLine  = { fg = c.cyanGreen, bold = true },
    DapUIBreakpointsLine         = { link = "DapUILineNumber" },
    DapUIBreakpointsDisabledLine = { fg = c.grey2 },
    DapUICurrentFrameName        = { link = "DapUIBreakpointsCurrentLine" },
    DapUIStepOver                = { fg = c.darkCyan },
    DapUIStepInto                = { fg = c.darkCyan },
    DapUIStepBack                = { fg = c.darkCyan },
    DapUIStepOut                 = { fg = c.darkCyan },
    DapUIStop                    = { fg = c.pinkNeon },
    DapUIPlayPause               = { fg = c.cyanGreen },
    DapUIRestart                 = { fg = c.cyanGreen },
    DapUIUnavailable             = { fg = c.grey2 },
    DapUIWinSelect               = { fg = c.darkCyan },
    DapUIEndofBuffer             = { link = "EndofBuffer" },
}
