local c = require("sigma.colors")

return {
    markdownBold              = { fg = c.gray7, style = 'bold' },
    markdownCode              = { fg = c.orange3 },
    markdownCodeBlock         = { fg = c.orange3 },
    markdownUrl               = { fg = c.purple2, style = 'underline' },
    markdownCodeError         = { fg = c.red3 },
    markdownH1                = { fg = c.cyan6 },
    markdownH2                = { fg = c.cyan6 },
    markdownH3                = { fg = c.cyan6 },
    markdownH4                = { fg = c.cyan6 },
    markdownH5                = { fg = c.cyan6 },
    markdownH6                = { fg = c.cyan6 },
    markdownId                = { fg = c.purple2 },
    markdownItalic            = { gf = c.gray7, style = 'italic' },
    markdownLinkText          = { fg = c.cyan6 },
    markdownRule              = { fg = c.accent },
    markdownListMarker        = { fg = c.red1 },
    markdownHeadingDelimiter  = { fg = c.cyan6 },
    markdownHeadingRule       = { fg = c.accent },
    markdownUrlTitleDelimiter = { fg = c.cyan3 },
    markdownCodeSpecial       = { fg = c.orange2 },
    markdownCodeDelimiter     = { fg = c.green1 },
    markdownBlockquote        = { fg = c.accent },
    markdownIdDeclaration     = { fg = c.cyan6 },
    markdownIdDelimiter       = { fg = c.gray6 },
    markdownLinkDelimiter     = { fg = c.gray6 },
    markdownOrderedListMarker = { fg = c.red1 },
}
