local c = require("sigma.colors")

return {
    markdownBold              = { fg = c.grey6, bold = true },
    markdownCode              = { fg = c.orangeDimmed },
    markdownCodeBlock         = { fg = c.orangeDimmed },
    markdownUrl               = { fg = c.redDanger, underline = true },
    markdownCodeError         = { fg = c.lightRed },
    markdownH1                = { fg = c.darkCyan },
    markdownH2                = { fg = c.darkCyan },
    markdownH3                = { fg = c.darkCyan },
    markdownH4                = { fg = c.darkCyan },
    markdownH5                = { fg = c.darkCyan },
    markdownH6                = { fg = c.darkCyan },
    markdownId                = { fg = c.redDanger },
    markdownItalic            = { fg = c.grey6, italic = true },
    markdownLinkText          = { fg = c.darkCyan },
    markdownRule              = { fg = c.accent },
    markdownListMarker        = { fg = c.redDanger },
    markdownHeadingDelimiter  = { fg = c.darkCyan },
    markdownHeadingRule       = { fg = c.accent },
    markdownUrlTitleDelimiter = { fg = c.lightCyan },
    markdownCodeSpecial       = { fg = c.darkOrange },
    markdownCodeDelimiter     = { fg = c.green },
    markdownBlockquote        = { fg = c.accent },
    markdownIdDeclaration     = { fg = c.darkCyan },
    markdownIdDelimiter       = { fg = c.grey5 },
    markdownLinkDelimiter     = { fg = c.grey5 },
    markdownOrderedListMarker = { fg = c.redDanger },
}
